# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8MNwlygIEnJHjy_i3uG0s02SCTIO4cdavA_nBljI1i5bj3fluttIN-g8DhN0UvQG-5EL_fuLquQXnBW0P7D_x7BXV0G2SBmOQgSr6Pv51Lh4qjODUnTMm4vGzU0e1s-7nvrLcYqm-9eIpyz3XAD1b6ApzUolVdRX8uoVv43GmEw96fQtka6Q0FDQuhpFRM9GT9Gk0dplc4XA6kKhgRW7M4dbvZ9tIfbffmrPwkW0vx6GrVTFyXN4rtxMiEinVlGktdZBylxlYRByKgEIrhmH7FgANT35GjGk2iAEBT0JpEUI4gl2P1iV9bo75m_AIUzRkm2VgX_CxkykvqNL8iv_jc5qG314mlIsYiVBCSBz9Skiy2-UWgD6ielaqz5VKHJUHfGi-jzK1fNLnCkSjMhZo01226_FMSSh3LhkQRlGkDT6_tNIVXZP0fsp2KAqaGCfJPxtgFsmMMJbm2lRimam5XcTBdn8irN7L9i6IGrFvLrTvLU3DhIKsmK5cUgJYdPKWjqDQmAvlRe4SbxWN5LCNEbLC9zJKh_fOIsCBTH6gXF64UjD9eQRRJS0QcyOu7QPrwceKtXlPYeT6TWAJLESvRffmMBZ4lqb8l6p5Vf81wGGulpQU5rc9Y4h9sjV2OEzTJT6mXDKVh1Oy_mmHCzXT-cCcty7IalWjBYMZv6nIrkeatxGSE3ZuwsAq-nxixwBJ-UAsE2XDua4BrCCEY1qaIoQFyIUqT7RY8gfRQbuRBxGks1-ycXbsnyb_C7hRmInxx-BwOJJrlM8ZG9Q4vXaZnHCHPgJbnC10CwTIjpoPUaeeVN8_pm6Z2x9bvPsZWpvQQ

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Awesome Title 4"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/5
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 5,
  "Title": "Updated Awesome Title"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=2&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 2,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}

###